# This is an action used for running tests on BrowserStack. DRI -> @ivana, @jovan, @emin

name: TestAction

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:

# auth with TIDAL
 auth:
  name: Get User Token 
  runs-on: ubuntu-latest
  
  steps:
# sending the login request to our BE which is using a separate client/secret for test login. This way we get ONLY the access token which is valid for 1hr
    - name: Fetch User Token
      id: loginRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://auth.tidal.com/v1/oauth2/token/
        method: 'POST'
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: 'client_id=CO2AMysgmXR2di4f&client_secret=qDEW8Zk4Ay6XtKAfZEDevosqVoVjm6MMHFd9tKKCU0g=&grant_type=password&scope=r_usr w_usr w_sub&username=iosautomation&password=qwerty'
       
    - name: Show token parts
      run: |
        echo ${{ fromJson(steps.loginRequest.outputs.response).access_token }} | fold -w90
    
# upload the IPA
 upload:
  name: Upload IPA
  runs-on: ubuntu-latest

  steps:

    - name: Upload IPA
      id: uploadIPArequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://postman-echo.com/post #https://api-cloud.browserstack.com/app-automate/xcuitest/v2/build
#        username: 'emingrbo_7jsnct'
#        password: 'VW2aXyJNeVNpd6KPEyxY'
        method: 'POST'
        files: '{ "file": "./test.txt" }'

      
# WORKING, BUT SET ASIDE FOR NOW ===========================
# start BS test execution
# initTest:
#  name: Execute Test
#  runs-on: ubuntu-latest
#
#  steps:
#
# init postman script
#     - name: Setup Node (required for Postman)
#       uses: actions/setup-node@v1
#       with:
#       	 node-version: '14.x'
#
#     - name: Install newman
#       run: |
#         npm install -g newman
#         npm install -g newman-reporter-html
#     - name: Run POSTMAN collection
#       run: >
#         newman
#         run $POSTMAN_COLLECTION_URL
#         -e $POSTMAN_ENVIRONMENT_URL
#
#    - name: Execute Test
#      uses: fjogeleit/http-request-action@v1
#      with:
#        url: https://api-cloud.browserstack.com/app-automate/xcuitest/v2/build
#        method: 'POST'
#        username: 'emingrbo_7jsnct'
#        password: 'VW2aXyJNeVNpd6KPEyxY'
#        customHeaders: '{"Content-Type": "application/json"}'
#        data: '{
#				"project" : "TIDAL-trials",
#				"app": "bs://91166b4e254b0d8460c07b207964deb3741a4a44",
#				"testSuite": "bs://42be4c6eb2f014999c4cab0585c2eee20dac5b2e",
#				"deviceLogs": "true",
#				"devices": ["iPhone 13-15"],
#				"isWirelessEnabled":"true",
#				"setEnvVariables":{
#				"testUserID": "178732065",
#				"testChannelID": "258",
#				"1tokenPT":"eyJraWQiOiJ2OU1GbFhqWSIsImFsZyI6IkVTMjU2In0.eyJ0eXBlIjoibzJfYWNjZXNzIiwidWlkIjoxNzg3MzIwNj",
#				"2tokenPT":"UsInNjb3BlIjoid19zdWIgcl91c3Igd191c3IiLCJnVmVyIjowLCJzVmVyIjowLCJjaWQiOjY4NjEsImV4cCI6MTY2",
#				"3tokenPT":"NDUzNjc0Mywic2lkIjoiN2RlZjJmZmMtZmQxOC00MDhiLWFiYzEtNzkxM2Y2YWJhMTU1IiwiaXNzIjoiaHR0cHM6Ly",
#				"4tokenPT":"9hdXRoLnRpZGFsLmNvbS92MSJ9.FJ3PcrfPlJ-2xZdgUAoAOiIaVSn_jnanegjdIOw-f2QRtmN2gZl3npqEpsq1heY",
#				"5tokenPT":"6nnnNs0GtUZUAcsv3q47fwA"
#				},
#				"networkLogs": "true",
#				"only-testing": ["TIDALUITestsEmptyUser"]
#				}'
