# This is an action used for running tests on BrowserStack. DRI -> @ivana, @jovan, @emin

name: TestAction

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:

# auth with TIDAL
 auth:
  name: Get User Token 
  runs-on: ubuntu-latest
  
  steps:
  
# sending the login request to our BE which is using a separate client/secret for test login. This way we get ONLY the access token which is valid for 1hr
    - name: Fetch User Token
      id: loginRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://auth.tidal.com/v1/oauth2/token/
        method: 'POST'
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: 'client_id=CO2AMysgmXR2di4f&client_secret=qDEW8Zk4Ay6XtKAfZEDevosqVoVjm6MMHFd9tKKCU0g=&grant_type=password&scope=r_usr w_usr w_sub&username=iosautomation&password=qwerty'
        
    - name: Show Response
      run: |
       echo ${{ steps.loginRequest.outputs.response }}
       echo ${{ steps.loginRequest.outputs.headers }}
       echo ${{ fromJson(steps.loginRequest.outputs.response).access_token }}
       
# we cannot send the token in full length to BS and need to split it into parts under 100 chars
    - name: Show token parts
      run: |
       bash.sh
       echo "abcdefg" | fold -w2 -s
