# This is an action used for running tests on BrowserStack. DRI -> @ivana, @jovan, @emin

name: TestAction

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:

 build:
  name: Get User Token 
  runs-on: ubuntu-latest
  
  steps:
 
#   - name: Use Node.js ${{ matrix.node-version }}
#     uses: actions/setup-node@v1
#     with:
#      node-version: ${{ matrix.node-version }}

#   - run: npm install
#   - run: npm install --legacy-peer-deps
#   - run: npm run build    
    
#   - name: Upload File
#     id: upload
#     uses: JantHsueh/upload-file-action@master
#     with:
#      url: auth.tidal.com/v1/oauth2/token
#      forms: '{"grant_type":"password", "client_id":"CO2AMysgmXR2di4f","client_secret":"qDEW8Zk4Ay6XtKAfZEDevosqVoVjm6MMHFd9tKKCU0g=","scope":"r_usr w_usr w_sub","username":"iosautomation","password":"qwerty"}'
#      fileForms: '{}'
     
#   - name: Show output
#     run: echo "🚨 OUTPUT 🚨"

#   - name: Bump before build
#     run: |
#      $output = '${{ steps.upload.outputs.output }}' | ConvertFrom-Json
#      Write-Host "Data from output: statusCode $($output.statusCode) data $($output.data)"

#     - name: Code check out
#       uses: dkershner6/post-api-call-action@v1
#       with:
#        url: auth.tidal.com/v1/oauth2/token/
#        headers: '{"Content-Type": "application/x-www-form-urlencoded"}'
#        params: '{"grant_type":"password", "client_id":"CO2AMysgmXR2di4f","client_secret":"qDEW8Zk4Ay6XtKAfZEDevosqVoVjm6MMHFd9tKKCU0g=","scope":"r_usr w_usr w_sub","username":"iosautomation","password":"qwerty"}'

#     - name: curl
#       uses: wei/curl@v1
#       with:
#         args: -X POST auth.tidal.com/v1/oauth2/token/

    - name: Login User
      id: loginRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://auth.tidal.com/v1/oauth2/token/
        method: 'POST'
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: 'client_id=CO2AMysgmXR2di4f&client_secret=qDEW8Zk4Ay6XtKAfZEDevosqVoVjm6MMHFd9tKKCU0g=&grant_type=password&scope=r_usr w_usr w_sub&username=iosautomation&password=qwerty'
        
    - name: Show Response
      run: |
       echo ${{ steps.loginRequest.outputs.response }}
       echo ${{ steps.loginRequest.outputs.headers }}
       echo ${{ fromJson(steps.loginRequest.outputs.response).field_you_want_to_access }}  
       
       
       
