# This is an action used for running tests on BrowserStack. DRI -> @ivana, @jovan, @emin

name: TestAction

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:

# auth with TIDAL
 auth:
  name: Get User Token 
  runs-on: ubuntu-latest
  
  steps:
  
# sending the login request to our BE which is using a separate client/secret for test login. This way we get ONLY the access token which is valid for 1hr
    - name: Fetch User Token
      id: loginRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://auth.tidal.com/v1/oauth2/token/
        method: 'POST'
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: 'client_id=CO2AMysgmXR2di4f&client_secret=qDEW8Zk4Ay6XtKAfZEDevosqVoVjm6MMHFd9tKKCU0g=&grant_type=password&scope=r_usr w_usr w_sub&username=iosautomation&password=qwerty'
       
    - name: Show token parts
      run: |
        echo ${{ fromJson(steps.loginRequest.outputs.response).access_token }} | fold -w90
        
# auth with TIDAL
 upload:
  name: Upload IPA
  runs-on: ubuntu-latest
  
  steps:
  
    - name: Upload IPA
      id: loginRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://auth.tidal.com/v1/oauth2/token/
        method: 'POST'
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        username: 'emingrbo_7jsnct'
        password: 'VW2aXyJNeVNpd6KPEyxY'
        data: '{ "custom_id": "test" }'
        files: '{ "file": "${{ github.workspace }}/test.ipa" }'
